## API #####
api:

  user:
    - url: "GET /login"
      custom: "login"
    - url: "GET /logout"
      custom: "logout"

    - url: "GET /user/get"
      action: "get"
    - url: "GET /user/list"
      action: "getList"
    - url: "POST /user/add"
      action: "add"
    - url: "PUT /user/update"
      action: "update"
    - url: "PUT /user/remove"
      action: "remove"
  tag:
    - url: "GET /tag/list"
      action: "getList"
    - url: "POST /tag/add"
      action: "add"

## 网页 #####
website:
  timeline:
    - url: "GET /site/login"
      template: "login"
      parameter:
        title: "login"
    - url: "GET /site/timeline"
      template: "timeline"
      parameter:
        title: "timeline"

  user:
    - url: "GET /site/user/list"
      template: "user"
      parameter:
        title: "user list"

  file:
    - url: "GET /admin/file/list"
      template: "datacenter/file_list"
      parameter:
        title: "file list"
        topmenu: "datacenter"
        sidemenu: "file"

## 重定向 #####
redirect:
  - url: "GET /"
    target: "/site/timeline"
